"""Abstract base class for activity generators.

All activity generators (mouse, keyboard, app interaction, VS Code)
inherit from this base and implement the required interface.
"""

from __future__ import annotations

import logging
import random
import time
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import TYPE_CHECKING, Any, Optional

if TYPE_CHECKING:
    from simulator.config import SimulatorConfig
    from simulator.logging.event_logger import EventLogger


class EventStatus(str, Enum):
    """Status of an activity event."""

    SUCCESS = "success"
    FAILURE = "failure"
    SKIPPED = "skipped"


@dataclass
class ActivityEvent:
    """Represents a single activity event generated by a generator.

    This is the standard event format logged by the EventLogger.
    """

    timestamp: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    event_type: str = ""  # e.g., "mouse_move", "key_press", "app_launch"
    action: str = ""  # Specific action description
    application: str = ""  # Target application name, if any
    success: bool = True
    error_message: Optional[str] = None
    details: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        """Convert event to dictionary for logging."""
        result = {
            "timestamp": self.timestamp,
            "event_type": self.event_type,
            "action": self.action,
            "application": self.application,
            "success": self.success,
        }
        if self.error_message:
            result["error_message"] = self.error_message
        if self.details:
            result["details"] = self.details
        return result


class BaseGenerator(ABC):
    """Abstract base class for activity generators.

    Provides common functionality for all generators including:
    - Configuration access
    - Logging integration
    - Error handling
    - Random number generation (seeded for reproducibility)
    """

    def __init__(
        self,
        config: SimulatorConfig,
        event_logger: EventLogger,
        rng: random.Random,
    ) -> None:
        """Initialize the generator.

        Args:
            config: Simulator configuration.
            event_logger: Event logger for recording actions.
            rng: Seeded random number generator for reproducibility.
        """
        self.config = config
        self.event_logger = event_logger
        self.rng = rng
        self.logger = logging.getLogger(self.__class__.__name__)
        self._dry_run = False

    @property
    def dry_run(self) -> bool:
        """Whether to run in dry-run mode (log but don't execute)."""
        return self._dry_run

    @dry_run.setter
    def dry_run(self, value: bool) -> None:
        self._dry_run = value

    @property
    @abstractmethod
    def generator_type(self) -> str:
        """Return the type identifier for this generator (e.g., 'mouse', 'keyboard')."""
        ...

    @abstractmethod
    def get_available_actions(self) -> list[str]:
        """Return list of action names this generator supports.

        Returns:
            List of action name strings.
        """
        ...

    @abstractmethod
    def _execute_action(self, action_name: str) -> ActivityEvent:
        """Execute a specific action (internal implementation).

        Subclasses implement this with the actual automation logic.

        Args:
            action_name: Name of the action to execute.

        Returns:
            ActivityEvent describing what happened.
        """
        ...

    def is_available(self) -> bool:
        """Check if this generator is available on the current platform.

        Override in subclasses to check for platform-specific dependencies.

        Returns:
            True if the generator can operate on this platform.
        """
        return True

    def execute(self, action_name: str) -> ActivityEvent:
        """Execute an action with error handling and logging.

        This is the public interface. It wraps _execute_action with
        error handling, dry-run support, and event logging.

        Args:
            action_name: Name of the action to execute.

        Returns:
            ActivityEvent describing the result.
        """
        if action_name not in self.get_available_actions():
            event = ActivityEvent(
                event_type=self.generator_type,
                action=action_name,
                success=False,
                error_message=f"Unknown action: {action_name}",
            )
            self.event_logger.log_event(event)
            return event

        if self.dry_run:
            self.logger.info("[DRY RUN] %s.%s", self.generator_type, action_name)
            event = ActivityEvent(
                event_type=self.generator_type,
                action=action_name,
                success=True,
                details={"dry_run": True},
            )
            self.event_logger.log_event(event)
            return event

        try:
            event = self._execute_action(action_name)
            self.event_logger.log_event(event)
            self.logger.debug("Executed %s.%s", self.generator_type, action_name)
            return event
        except Exception as e:
            self.logger.error(
                "Failed to execute %s.%s: %s", self.generator_type, action_name, e
            )
            event = ActivityEvent(
                event_type=self.generator_type,
                action=action_name,
                success=False,
                error_message=str(e),
            )
            self.event_logger.log_event(event)
            return event

    def random_delay(self, min_seconds: float = 0.1, max_seconds: float = 1.0) -> None:
        """Sleep for a random duration within the given range.

        Uses the seeded RNG for reproducible timing in non-dry-run mode.

        Args:
            min_seconds: Minimum delay in seconds.
            max_seconds: Maximum delay in seconds.
        """
        delay = self.rng.uniform(min_seconds, max_seconds)
        if not self.dry_run:
            time.sleep(delay)

    def pick_random_action(self) -> str:
        """Pick a random action from available actions.

        Returns:
            A randomly selected action name.
        """
        actions = self.get_available_actions()
        return self.rng.choice(actions)
